name: Docker Image CI

on:
  push:
    branches: ["rajenthz-main"]
  pull_request:
    branches: ["rajenthz-main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Mix Check
        run: mix check
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
